/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as WebchatRouteImport } from './routes/webchat'
import { Route as SimuladorRouteImport } from './routes/simulador'
import { Route as PrevisaoEscalaRouteImport } from './routes/previsao-escala'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as OraculoRouteImport } from './routes/oraculo'
import { Route as EscalaRouteImport } from './routes/escala'
import { Route as ContratacoesRouteImport } from './routes/contratacoes'
import { Route as CapacidadeRouteImport } from './routes/capacidade'
import { Route as CalculadoraAnualRouteImport } from './routes/calculadora-anual'
import { Route as IndexRouteImport } from './routes/index'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/whatsapp.lazy').then((d) => d.Route))
const WebchatRoute = WebchatRouteImport.update({
  id: '/webchat',
  path: '/webchat',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/webchat.lazy').then((d) => d.Route))
const SimuladorRoute = SimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/simulador.lazy').then((d) => d.Route))
const PrevisaoEscalaRoute = PrevisaoEscalaRouteImport.update({
  id: '/previsao-escala',
  path: '/previsao-escala',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/previsao-escala.lazy').then((d) => d.Route),
)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/painel.lazy').then((d) => d.Route))
const OraculoRoute = OraculoRouteImport.update({
  id: '/oraculo',
  path: '/oraculo',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/oraculo.lazy').then((d) => d.Route))
const EscalaRoute = EscalaRouteImport.update({
  id: '/escala',
  path: '/escala',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/escala.lazy').then((d) => d.Route))
const ContratacoesRoute = ContratacoesRouteImport.update({
  id: '/contratacoes',
  path: '/contratacoes',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/contratacoes.lazy').then((d) => d.Route))
const CapacidadeRoute = CapacidadeRouteImport.update({
  id: '/capacidade',
  path: '/capacidade',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/capacidade.lazy').then((d) => d.Route))
const CalculadoraAnualRoute = CalculadoraAnualRouteImport.update({
  id: '/calculadora-anual',
  path: '/calculadora-anual',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/calculadora-anual.lazy').then((d) => d.Route),
)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculadora-anual': typeof CalculadoraAnualRoute
  '/capacidade': typeof CapacidadeRoute
  '/contratacoes': typeof ContratacoesRoute
  '/escala': typeof EscalaRoute
  '/oraculo': typeof OraculoRoute
  '/painel': typeof PainelRoute
  '/previsao-escala': typeof PrevisaoEscalaRoute
  '/simulador': typeof SimuladorRoute
  '/webchat': typeof WebchatRoute
  '/whatsapp': typeof WhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculadora-anual': typeof CalculadoraAnualRoute
  '/capacidade': typeof CapacidadeRoute
  '/contratacoes': typeof ContratacoesRoute
  '/escala': typeof EscalaRoute
  '/oraculo': typeof OraculoRoute
  '/painel': typeof PainelRoute
  '/previsao-escala': typeof PrevisaoEscalaRoute
  '/simulador': typeof SimuladorRoute
  '/webchat': typeof WebchatRoute
  '/whatsapp': typeof WhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculadora-anual': typeof CalculadoraAnualRoute
  '/capacidade': typeof CapacidadeRoute
  '/contratacoes': typeof ContratacoesRoute
  '/escala': typeof EscalaRoute
  '/oraculo': typeof OraculoRoute
  '/painel': typeof PainelRoute
  '/previsao-escala': typeof PrevisaoEscalaRoute
  '/simulador': typeof SimuladorRoute
  '/webchat': typeof WebchatRoute
  '/whatsapp': typeof WhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculadora-anual'
    | '/capacidade'
    | '/contratacoes'
    | '/escala'
    | '/oraculo'
    | '/painel'
    | '/previsao-escala'
    | '/simulador'
    | '/webchat'
    | '/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculadora-anual'
    | '/capacidade'
    | '/contratacoes'
    | '/escala'
    | '/oraculo'
    | '/painel'
    | '/previsao-escala'
    | '/simulador'
    | '/webchat'
    | '/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/calculadora-anual'
    | '/capacidade'
    | '/contratacoes'
    | '/escala'
    | '/oraculo'
    | '/painel'
    | '/previsao-escala'
    | '/simulador'
    | '/webchat'
    | '/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculadoraAnualRoute: typeof CalculadoraAnualRoute
  CapacidadeRoute: typeof CapacidadeRoute
  ContratacoesRoute: typeof ContratacoesRoute
  EscalaRoute: typeof EscalaRoute
  OraculoRoute: typeof OraculoRoute
  PainelRoute: typeof PainelRoute
  PrevisaoEscalaRoute: typeof PrevisaoEscalaRoute
  SimuladorRoute: typeof SimuladorRoute
  WebchatRoute: typeof WebchatRoute
  WhatsappRoute: typeof WhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webchat': {
      id: '/webchat'
      path: '/webchat'
      fullPath: '/webchat'
      preLoaderRoute: typeof WebchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/previsao-escala': {
      id: '/previsao-escala'
      path: '/previsao-escala'
      fullPath: '/previsao-escala'
      preLoaderRoute: typeof PrevisaoEscalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oraculo': {
      id: '/oraculo'
      path: '/oraculo'
      fullPath: '/oraculo'
      preLoaderRoute: typeof OraculoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escala': {
      id: '/escala'
      path: '/escala'
      fullPath: '/escala'
      preLoaderRoute: typeof EscalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratacoes': {
      id: '/contratacoes'
      path: '/contratacoes'
      fullPath: '/contratacoes'
      preLoaderRoute: typeof ContratacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacidade': {
      id: '/capacidade'
      path: '/capacidade'
      fullPath: '/capacidade'
      preLoaderRoute: typeof CapacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-anual': {
      id: '/calculadora-anual'
      path: '/calculadora-anual'
      fullPath: '/calculadora-anual'
      preLoaderRoute: typeof CalculadoraAnualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculadoraAnualRoute: CalculadoraAnualRoute,
  CapacidadeRoute: CapacidadeRoute,
  ContratacoesRoute: ContratacoesRoute,
  EscalaRoute: EscalaRoute,
  OraculoRoute: OraculoRoute,
  PainelRoute: PainelRoute,
  PrevisaoEscalaRoute: PrevisaoEscalaRoute,
  SimuladorRoute: SimuladorRoute,
  WebchatRoute: WebchatRoute,
  WhatsappRoute: WhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
